steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/curalina:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/curalina:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - curalina-git-2
      - --image=gcr.io/$PROJECT_ID/curalina:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed


options:
  logging: CLOUD_LOGGING_ONLY
